import './admin';
import './choose-file';
import './code-block';
import './debug';
import './edit-exercise';
import './exercises-list';
import './page-header';
import './sandbox';
import './variable';